version: '3.9'

services:
  react:
    build: frontend
    container_name: presentation_tier
    restart: unless-stopped
    ports:
      - "9333:9333"
    links:
      - flask

  flask:
    build: backend
    container_name: logic_tier
    restart: unless-stopped
    environment:
      - FLASK_APP=backend/app
    ports:
      - "5000:5000"
    links:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: data_tier
    restart: unless-stopped
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=vdt2022
      - MONGO_INITDB_ROOT_USERNAME=practice3
      - MONGO_INITDB_ROOT_PASSWORD=practice3
    ports:
      - "27017:27017"
      