---
- name: Copy Grafana Config File
  copy: 
    src: ./provisioning
    dest: ~/grafana/

- name: Create Grafana container
  docker_container:
    image: grafana/grafana
    name: grafana
    ports:
    - 4000:3000
    volumes:
    - grafana-db:/var/lib/grafana
    - ~/grafana/provisioning/:/etc/grafana/provisioning/