global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

rule_files:
  - 'alert.rules.yml'

scrape_configs: 
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['nodeexporter:9100']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
      - '192.168.1.176:9093'