global:
scrape_interval: 15s 
evaluation_interval: 15s 

# Alertmanager configuration
 alerting:
   alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

 rule_files:
- 'alert.rules.yml'

scrape_configs: 
- job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['localhost:9090']

- job_name: 'node_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9100']