- name: Create Docker context for Grafana
  become_user: haivm
  shell: docker context create {{item.name}} --docker "host=ssh://root@{{item.ip}}"
  ignore_errors: true
  tags: 
    - local
  loop: 
    - {name: 'Grafana1', ip: '178.128.101.240'} 
    - {name: 'Grafana2', ip: '178.128.103.48'}

- name: Deploy Grafana on Grafana nodes
  become_user: haivm
  shell: | 
    docker context use {{item.name}} 
    docker-compose -f {{item.file_path}} pull
    docker-compose -f {{item.file_path}} up -d
  ignore_errors: true
  tags: 
    - local
  loop:
    - {name: 'Grafana1', file_path: '/home/haivm/Documents/Viettel-Digital-Talent-Program-2022/Practice-4/Tran-Quang-Hai/ha/docker-compose.yml'}
    - {name: 'Grafana2', file_path: '/home/haivm/Documents/Viettel-Digital-Talent-Program-2022/Practice-4/Tran-Quang-Hai/ha/docker-compose.yml'}