- hosts: servers
  become: true
  roles:
    - servers

- hosts: grafana
  become: true
  roles: 
    - grafana

- hosts: prometheus
  become: true
  roles:
    - prometheus

- hosts: ha
  become: true
  roles:
    - ha
  
- hosts: local
  become: true
  roles:
    - local
  tags: 
    - local
