route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#huhuhuhuhuhu'
            api_url: 'https://hooks.slack.com/services/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'