version: '3.0'

services:
  mongodb:
    image: mongo:5.0
    restart: always
    container_name: mongodb_vt
    ports:
      - 27017:27017
  pythonapp:
    image: haitranquangofficial/viettel:hw3-python
    restart: always
    ports:
      - 5000:5000
  nginx:
    image: haitranquangofficial/viettel:hw3-nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - pythonapp