route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'huong.set'
            channel: '#practice4'
            api_url: 'https://hooks.slack.com/services/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'
